[project]
name = "activities-repository"
version = "1.0.0"
requires-python= ">=3.10"
dependencies = [
    "gatorgrade",
    "mypy",
    "pytest",
    "mpremote",
    "micropython-rp2-pico-stubs"
]

[tool.pytest]
testpaths = [
    "tests"
]