name: Activity One

on:
  push:
    branches: [main]
  fork:
    branches: [main]

jobs:
  grade:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.1
      with:
        fetch-depth: '0'
    - name: Setup Python
      if: always()
      uses: actions/setup-python@v6.1.0
      with:
        python-version: 3.12
    - name: Set up grading environment
      run: |
        sudo apt-get update
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install gatorgrade --ignore-installed PyYAML --break-system-packages
    - name: Grade repository
      run: |
        source .venv/bin/activate
        cd src/activity_one && gatorgrade --config .gatorgrade.yml
      if: always()
      env:
        PIPENV_VENV_IN_PROJECT: 1
        PIPENV_IGNORE_VIRTUALENVS: 1